name: Tests
on:
  push:
    branches:
      - master
      - staging

  pull_request:
    branches:
      - master
      - staging

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
      with:
        skip_adding_nixpkgs_channel: true
    - name: Running tests
      run: nix-build channel/tests -k
