name: Tests
on:
  push:
    branches:
      - master
      - staging

  pull_request:
    branches:
      - master
      - staging

jobs:
  test-channel:
    name: Channel construction tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
    - name: Building test script
      run: nix-build channel/tests
    - name: Running test script
      run: ./result

  test:
    name: Flox channel tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
    - name: Building test script
      run: nix-build tests
    - name: Running test script
      run: ./result

  codespell:
    name: Codespell
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
    - name: Install codespell
      run: nix-env -f channel:nixos-20.09 -iA codespell
    - uses: codespell-project/codespell-problem-matcher@v1
    - name: Running codespell
      run: |
        # -q 2 to hide warnings about binary files
        git ls-files | xargs codespell -q 2
